# Generated by Django 5.1 on 2024-09-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='owner_name',
            field=models.CharField(max_length=240, verbose_name='Owner Name'),
        ),
    ]
